-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2020-05-30 18:53:19.444

-- tables
-- Table: CERTYFIKAT
CREATE TABLE CERTYFIKAT (
    ID_CERTYFIKAT bigint NOT NULL,
    PROBA_ID_PROBA bigint NOT NULL,
    KRAJ_ID_KRAJ bigint NOT NULL,
    CONSTRAINT CERTYFIKAT_pk PRIMARY KEY (ID_CERTYFIKAT)
);

-- Table: DOSTAWCA
CREATE TABLE DOSTAWCA (
    ID_DOSTAWCA bigint NOT NULL,
    NAZWA varchar(50) NOT NULL,
    MIASTO varchar(50) NOT NULL,
    ULICA varchar(50) NOT NULL,
    NR_DOMU_LOKALU varchar(10) NOT NULL,
    CONSTRAINT DOSTAWCA_pk PRIMARY KEY (ID_DOSTAWCA)
);

-- Table: DYSTRYBUCJA_PROBY
CREATE TABLE DYSTRYBUCJA_PROBY (
    ID_DYSTRYBUCJA_PROBY bigint NOT NULL,
    PROBA_ID_PROBA bigint NOT NULL,
    LABORATORIUM_ID_LABORATORIUM bigint NOT NULL,
    ILOSC_PROBY decimal(5,2) NOT NULL,
    CONSTRAINT DYSTRYBUCJA_PROBY_pk PRIMARY KEY (ID_DYSTRYBUCJA_PROBY)
);

-- Table: ETAP_PROD
CREATE TABLE ETAP_PROD (
    ID_ETAP_PROD bigint NOT NULL,
    NAZWA_ETAPU varchar(30) NOT NULL,
    CONSTRAINT ETAP_PROD_pk PRIMARY KEY (ID_ETAP_PROD)
);

-- Table: FUNKCJA
CREATE TABLE FUNKCJA (
    ID_FUNKCJA bigint NOT NULL,
    NAZWA_FUNKCJI varchar(30) NOT NULL,
    CONSTRAINT FUNKCJA_pk PRIMARY KEY (ID_FUNKCJA)
);

-- Table: JEDNOSTKA_MIARY
CREATE TABLE JEDNOSTKA_MIARY (
    ID_JEDNOSTKA_MIARY bigint NOT NULL,
    SYMBOL_JEDNOSTKI varchar(10) NOT NULL,
    CONSTRAINT JEDNOSTKA_MIARY_pk PRIMARY KEY (ID_JEDNOSTKA_MIARY)
);

-- Table: KRAJ
CREATE TABLE KRAJ (
    ID_KRAJ bigint NOT NULL,
    NAZWA varchar(50) NOT NULL,
    JEZYK varchar(20) NOT NULL,
    CONSTRAINT KRAJ_pk PRIMARY KEY (ID_KRAJ)
);

-- Table: LABORATORIUM
CREATE TABLE LABORATORIUM (
    ID_LABORATORIUM bigint NOT NULL,
    NAZWA varchar(50) NOT NULL,
    CONSTRAINT LABORATORIUM_pk PRIMARY KEY (ID_LABORATORIUM)
);

-- Table: OCENA
CREATE TABLE OCENA (
    ID_OCENA bigint NOT NULL,
    NAZWA_OCENY varchar(50) NOT NULL,
    CONSTRAINT OCENA_pk PRIMARY KEY (ID_OCENA)
);

-- Table: PARAMETR
CREATE TABLE PARAMETR (
    ID_PARAMETR bigint NOT NULL,
    NAZWA_BADANIA varchar(50) NOT NULL,
    TYP_BADANIA varchar(30) NOT NULL,
    WYMAGANIA varchar(50) NOT NULL,
    SPECYFIKACJA_ID_SPECYFIKACJI bigint NOT NULL,
    CONSTRAINT PARAMETR_pk PRIMARY KEY (ID_PARAMETR)
);

-- Table: POMIAR
CREATE TABLE POMIAR (
    ID_POMIAR bigint NOT NULL,
    WARTOSC decimal(9,3) NOT NULL,
    WYNIK_ID_WYNIK bigint NOT NULL,
    CONSTRAINT POMIAR_pk PRIMARY KEY (ID_POMIAR)
);

-- Table: PRACOWNIK
CREATE TABLE PRACOWNIK (
    ID_PRACOWNIKA bigint NOT NULL,
    IMIE varchar(20) NOT NULL,
    NAZWISKO varchar(20) NOT NULL,
    STANOWISKO varchar(30) NOT NULL,
    FUNKCJA_ID_FUNKCJA bigint NOT NULL,
    CONSTRAINT PRACOWNIK_pk PRIMARY KEY (ID_PRACOWNIKA)
);

-- Table: PROBA
CREATE TABLE PROBA (
    ID_PROBA bigint NOT NULL,
    NR_PROBY varchar(20) NOT NULL,
    NR_SERII varchar(10) NOT NULL,
    SPECYFIKACJA_ID_SPECYFIKACJI bigint NOT NULL,
    NR_SERII_WYTWORCY varchar(20) NOT NULL,
    DOSTAWCA_ID_DOSTAWCA bigint NOT NULL,
    ETAP_PROD_ID_ETAP_PROD bigint NOT NULL,
    TYP_PROBY_ID_TYP_PROBY bigint NOT NULL,
    DATA_POBORU date NOT NULL,
    DATA_PRODUKCJI date NOT NULL,
    DATA_WAZNOSCI date NOT NULL,
    OCENA_ID_OCENA bigint NULL,
    OCENIONA bool NULL,
    DATA_OCENY timestamp NULL,
    SPRAWDZONA bool NULL,
    DATA_SPRAWDZENIA timestamp NULL,
    CONSTRAINT PROBA_pk PRIMARY KEY (ID_PROBA)
);

-- Table: SPECYFIKACJA
CREATE TABLE SPECYFIKACJA (
    ID_SPECYFIKACJI bigint NOT NULL,
    NAZWA_MATERIALU varchar(30) NOT NULL,
    SYMBOL_SPECYFIKACJI varchar(20) NOT NULL,
    CONSTRAINT SPECYFIKACJA_pk PRIMARY KEY (ID_SPECYFIKACJI)
);

-- Table: TYP_PROBY
CREATE TABLE TYP_PROBY (
    ID_TYP_PROBY bigint NOT NULL,
    NAZWA_TYPU varchar(30) NOT NULL,
    CONSTRAINT TYP_PROBY_pk PRIMARY KEY (ID_TYP_PROBY)
);

-- Table: UPRAWNIENIA
CREATE TABLE UPRAWNIENIA (
    ID_UPRAWNIENIA bigint NOT NULL,
    NAZWA_UPRAWNIENIA varchar(30) NOT NULL,
    CONSTRAINT UPRAWNIENIA_pk PRIMARY KEY (ID_UPRAWNIENIA)
);

-- Table: UPRAWNIENIA_FUNKCJI
CREATE TABLE UPRAWNIENIA_FUNKCJI (
    ID_UPRAWNIENIA_FUNKCJI bigint NOT NULL,
    FUNKCJA_ID_FUNKCJA bigint NOT NULL,
    UPRAWNIENIA_ID_UPRAWNIENIA bigint NOT NULL,
    CONSTRAINT UPRAWNIENIA_FUNKCJI_pk PRIMARY KEY (ID_UPRAWNIENIA_FUNKCJI)
);

-- Table: URZADZENIE
CREATE TABLE URZADZENIE (
    ID_URZADZENIA bigint NOT NULL,
    NAZWA_URZADZENIA varchar(30) NOT NULL,
    DATA_KALIBRACJI date NOT NULL,
    OKRES_KALIBRACJI int NOT NULL,
    CONSTRAINT URZADZENIE_pk PRIMARY KEY (ID_URZADZENIA)
);

-- Table: WYNIK
CREATE TABLE WYNIK (
    ID_WYNIK bigint NOT NULL,
    PROBA_ID_PROBA bigint NOT NULL,
    NAZWA_BADANIA varchar(50) NOT NULL,
    ZAKONCZONY bool NULL,
    DATA_WYKONANIA timestamp NULL,
    SPRAWDZONY bool NULL,
    DATA_SPRAWDZENIA timestamp NULL,
    SREDNIA decimal(9,3) NULL,
    MIN_W decimal(9,3) NULL,
    MAX_W decimal(9,3) NULL,
    OPIS_WYNIKU varchar(20) NULL,
    UWAGI varchar(250) NULL,
    TYP_BADANIA varchar(10) NOT NULL,
    PRACOWNIK_ID_PRACOWNIKA bigint NOT NULL,
    JEDN_MIARY_ID_JEDN_MIARY bigint NOT NULL,
    URZADZENIE_ID_URZADZENIA bigint NOT NULL,
    WYMAGANIA varchar(50) NOT NULL,
    CONSTRAINT WYNIK_pk PRIMARY KEY (ID_WYNIK)
);

-- foreign keys
-- Reference: CERTYFIKAT_KRAJ (table: CERTYFIKAT)
ALTER TABLE CERTYFIKAT ADD CONSTRAINT CERTYFIKAT_KRAJ FOREIGN KEY CERTYFIKAT_KRAJ (KRAJ_ID_KRAJ)
    REFERENCES KRAJ (ID_KRAJ);

-- Reference: CERTYFIKAT_PROBA (table: CERTYFIKAT)
ALTER TABLE CERTYFIKAT ADD CONSTRAINT CERTYFIKAT_PROBA FOREIGN KEY CERTYFIKAT_PROBA (PROBA_ID_PROBA)
    REFERENCES PROBA (ID_PROBA);

-- Reference: DYSTRYBUCJA_PROBY_LABORATORIUM (table: DYSTRYBUCJA_PROBY)
ALTER TABLE DYSTRYBUCJA_PROBY ADD CONSTRAINT DYSTRYBUCJA_PROBY_LABORATORIUM FOREIGN KEY DYSTRYBUCJA_PROBY_LABORATORIUM (LABORATORIUM_ID_LABORATORIUM)
    REFERENCES LABORATORIUM (ID_LABORATORIUM);

-- Reference: DYSTRYBUCJA_PROBY_PROBA (table: DYSTRYBUCJA_PROBY)
ALTER TABLE DYSTRYBUCJA_PROBY ADD CONSTRAINT DYSTRYBUCJA_PROBY_PROBA FOREIGN KEY DYSTRYBUCJA_PROBY_PROBA (PROBA_ID_PROBA)
    REFERENCES PROBA (ID_PROBA);

-- Reference: PARAMETR_SPECYFIKACJA (table: PARAMETR)
ALTER TABLE PARAMETR ADD CONSTRAINT PARAMETR_SPECYFIKACJA FOREIGN KEY PARAMETR_SPECYFIKACJA (SPECYFIKACJA_ID_SPECYFIKACJI)
    REFERENCES SPECYFIKACJA (ID_SPECYFIKACJI);

-- Reference: POMIAR_WYNIK (table: POMIAR)
ALTER TABLE POMIAR ADD CONSTRAINT POMIAR_WYNIK FOREIGN KEY POMIAR_WYNIK (WYNIK_ID_WYNIK)
    REFERENCES WYNIK (ID_WYNIK);

-- Reference: PRACOWNIK_FUNKCJA (table: PRACOWNIK)
ALTER TABLE PRACOWNIK ADD CONSTRAINT PRACOWNIK_FUNKCJA FOREIGN KEY PRACOWNIK_FUNKCJA (FUNKCJA_ID_FUNKCJA)
    REFERENCES FUNKCJA (ID_FUNKCJA);

-- Reference: PROBA_DOSTAWCA (table: PROBA)
ALTER TABLE PROBA ADD CONSTRAINT PROBA_DOSTAWCA FOREIGN KEY PROBA_DOSTAWCA (DOSTAWCA_ID_DOSTAWCA)
    REFERENCES DOSTAWCA (ID_DOSTAWCA);

-- Reference: PROBA_ETAP_PRODUKCJI (table: PROBA)
ALTER TABLE PROBA ADD CONSTRAINT PROBA_ETAP_PRODUKCJI FOREIGN KEY PROBA_ETAP_PRODUKCJI (ETAP_PROD_ID_ETAP_PROD)
    REFERENCES ETAP_PROD (ID_ETAP_PROD);

-- Reference: PROBA_OCENA (table: PROBA)
ALTER TABLE PROBA ADD CONSTRAINT PROBA_OCENA FOREIGN KEY PROBA_OCENA (OCENA_ID_OCENA)
    REFERENCES OCENA (ID_OCENA);

-- Reference: PROBA_SPECYFIKACJA (table: PROBA)
ALTER TABLE PROBA ADD CONSTRAINT PROBA_SPECYFIKACJA FOREIGN KEY PROBA_SPECYFIKACJA (SPECYFIKACJA_ID_SPECYFIKACJI)
    REFERENCES SPECYFIKACJA (ID_SPECYFIKACJI);

-- Reference: PROBA_TYP_PROBY (table: PROBA)
ALTER TABLE PROBA ADD CONSTRAINT PROBA_TYP_PROBY FOREIGN KEY PROBA_TYP_PROBY (TYP_PROBY_ID_TYP_PROBY)
    REFERENCES TYP_PROBY (ID_TYP_PROBY);

-- Reference: UPRAWNIENIA_FUNKCJI_FUNKCJA (table: UPRAWNIENIA_FUNKCJI)
ALTER TABLE UPRAWNIENIA_FUNKCJI ADD CONSTRAINT UPRAWNIENIA_FUNKCJI_FUNKCJA FOREIGN KEY UPRAWNIENIA_FUNKCJI_FUNKCJA (FUNKCJA_ID_FUNKCJA)
    REFERENCES FUNKCJA (ID_FUNKCJA);

-- Reference: UPRAWNIENIA_FUNKCJI_UPR (table: UPRAWNIENIA_FUNKCJI)
ALTER TABLE UPRAWNIENIA_FUNKCJI ADD CONSTRAINT UPRAWNIENIA_FUNKCJI_UPR FOREIGN KEY UPRAWNIENIA_FUNKCJI_UPR (UPRAWNIENIA_ID_UPRAWNIENIA)
    REFERENCES UPRAWNIENIA (ID_UPRAWNIENIA);

-- Reference: WYNIK_JEDNOSTKA_MIARY (table: WYNIK)
ALTER TABLE WYNIK ADD CONSTRAINT WYNIK_JEDNOSTKA_MIARY FOREIGN KEY WYNIK_JEDNOSTKA_MIARY (JEDN_MIARY_ID_JEDN_MIARY)
    REFERENCES JEDNOSTKA_MIARY (ID_JEDNOSTKA_MIARY);

-- Reference: WYNIK_PRACOWNIK (table: WYNIK)
ALTER TABLE WYNIK ADD CONSTRAINT WYNIK_PRACOWNIK FOREIGN KEY WYNIK_PRACOWNIK (PRACOWNIK_ID_PRACOWNIKA)
    REFERENCES PRACOWNIK (ID_PRACOWNIKA);

-- Reference: WYNIK_PROBA (table: WYNIK)
ALTER TABLE WYNIK ADD CONSTRAINT WYNIK_PROBA FOREIGN KEY WYNIK_PROBA (PROBA_ID_PROBA)
    REFERENCES PROBA (ID_PROBA);

-- Reference: WYNIK_URZADZENIE (table: WYNIK)
ALTER TABLE WYNIK ADD CONSTRAINT WYNIK_URZADZENIE FOREIGN KEY WYNIK_URZADZENIE (URZADZENIE_ID_URZADZENIA)
    REFERENCES URZADZENIE (ID_URZADZENIA);

-- End of file.

