-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2020-06-13 11:54:51.141

-- foreign keys
ALTER TABLE CERTYFIKAT
    DROP FOREIGN KEY CERTYFIKAT_KRAJ;

ALTER TABLE CERTYFIKAT
    DROP FOREIGN KEY CERTYFIKAT_PROBA;

ALTER TABLE DYSTRYBUCJA_PROBY
    DROP FOREIGN KEY DYSTRYBUCJA_PROBY_LABORATORIUM;

ALTER TABLE DYSTRYBUCJA_PROBY
    DROP FOREIGN KEY DYSTRYBUCJA_PROBY_PROBA;

ALTER TABLE PARAMETR
    DROP FOREIGN KEY PARAMETR_SPECYFIKACJA;

ALTER TABLE POMIAR
    DROP FOREIGN KEY POMIAR_WYNIK;

ALTER TABLE PRACOWNIK
    DROP FOREIGN KEY PRACOWNIK_FUNKCJA;

ALTER TABLE PROBA
    DROP FOREIGN KEY PROBA_DOSTAWCA;

ALTER TABLE PROBA
    DROP FOREIGN KEY PROBA_ETAP_PRODUKCJI;

ALTER TABLE PROBA
    DROP FOREIGN KEY PROBA_OCENA;

ALTER TABLE PROBA
    DROP FOREIGN KEY PROBA_SPECYFIKACJA;

ALTER TABLE PROBA
    DROP FOREIGN KEY PROBA_TYP_PROBY;

ALTER TABLE UPRAWNIENIA_FUNKCJI
    DROP FOREIGN KEY UPRAWNIENIA_FUNKCJI_FUNKCJA;

ALTER TABLE UPRAWNIENIA_FUNKCJI
    DROP FOREIGN KEY UPRAWNIENIA_FUNKCJI_UPR;

ALTER TABLE WYNIK
    DROP FOREIGN KEY WYNIK_JEDNOSTKA_MIARY;

ALTER TABLE WYNIK
    DROP FOREIGN KEY WYNIK_PRACOWNIK;

ALTER TABLE WYNIK
    DROP FOREIGN KEY WYNIK_PROBA;

ALTER TABLE WYNIK
    DROP FOREIGN KEY WYNIK_URZADZENIE;

-- tables
DROP TABLE CERTYFIKAT;

DROP TABLE DOSTAWCA;

DROP TABLE DYSTRYBUCJA_PROBY;

DROP TABLE ETAP_PROD;

DROP TABLE FUNKCJA;

DROP TABLE JEDNOSTKA_MIARY;

DROP TABLE KRAJ;

DROP TABLE LABORATORIUM;

DROP TABLE OCENA;

DROP TABLE PARAMETR;

DROP TABLE POMIAR;

DROP TABLE PRACOWNIK;

DROP TABLE PROBA;

DROP TABLE SPECYFIKACJA;

DROP TABLE TYP_PROBY;

DROP TABLE UPRAWNIENIA;

DROP TABLE UPRAWNIENIA_FUNKCJI;

DROP TABLE URZADZENIE;

DROP TABLE WYNIK;

-- End of file.

